import { expect, test } from '@playwright/test';
import { ids, payPayload, splitPayload, createPayload, voidPayload } from '../contracts/fixtures.ts';
import { pairAndUnlock, unlock, openPayment, openRecovery, watchWrites, installPrintCounter, printCount, closeReceipt, serverHarness as h } from './idempotencyHarness.ts';

test.afterEach(()=>h.clock(null));
test('TC-IDEM-084/e2e an unsupported capability blocks writes without falling back to old RPCs or mock',async({page})=>{
  await h.reset('F1');await page.route('**/rest/v1/rpc/get_write_capabilities',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({writeProtocolVersion:2,maxPayloadBytes:262144,pendingTtlSeconds:86400})}));
  await pairAndUnlock(page);await openPayment(page);const writes=watchWrites(page);let oldRpc=0;page.on('request',request=>{if(/\/rpc\/(pay_order|pay_order_items|submit_order_changes|void_order)$/.test(request.url()))oldRpc++;});await page.getByTestId('pay-button-footer').click();await expect(page.getByRole('status').filter({hasText:'Phiên bản ứng dụng và server chưa tương thích. Tạm dừng ghi và tải lại ứng dụng.'})).toBeVisible();expect(writes).toHaveLength(0);expect(oldRpc).toBe(0);expect((await h.snapshot()).payments).toHaveLength(0);
});
test('TC-IDEM-089/e2e unsent draft exit requires confirmation and keeping it emits no writes',async({page})=>{
  await h.reset();await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await page.getByTestId(`menu-item-${ids.M_T}`).click();const writes=watchWrites(page);await page.getByTestId('order-close-button').click();await expect(page.getByText('Bỏ đơn chưa gửi?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Tiếp tục chỉnh sửa',exact:true}).click();await expect(page.getByTestId('order-cart-line')).toHaveCount(1);expect(writes).toHaveLength(0);expect((await h.snapshot()).orders).toHaveLength(0);
});
test('TC-IDEM-051/e2e disabled print preference and recovery never auto-open or print a receipt',async({page})=>{
  await h.reset('F7');await installPrintCounter(page);await pairAndUnlock(page);await openPayment(page);await page.getByTestId('print-receipt-checkbox').uncheck();await page.getByTestId('pay-button-footer').click();await expect(page.getByTestId('payment-drawer')).toBeHidden();await expect(page.getByTestId('receipt-preview')).toBeHidden();expect(await printCount(page)).toBe(0);const raw=await h.snapshot();const key=raw.write_operations[0].operation_id;await openRecovery(page,key);await expect(page.getByTestId('historical-result')).toContainText('80.000');await expect(page.getByTestId('receipt-preview')).toBeHidden();expect(await printCount(page)).toBe(0);
});
for(const scenario of [{id:'044',fixture:'F1',remaining:120000},{id:'045',fixture:'F2',remaining:35000}] as const)test(`TC-IDEM-${scenario.id}/e2e lost split ACK replays the original payload after polling changes selection`,async({page})=>{
  await h.reset(scenario.fixture);await installPrintCounter(page);await pairAndUnlock(page);await openPayment(page);
  await page.getByTestId('pay-select-all').uncheck();if(scenario.fixture==='F1')await page.getByTestId('pay-item-plus').first().click();else await page.getByTestId('pay-item-checkbox').first().check();
  await page.getByTestId('payment-received-amount').fill('50000');const writes=watchWrites(page);let lost=false;
  await page.route('**/rest/v1/rpc/execute_write_operation',async route=>{
    if(lost){await route.continue();return;}const response=await route.fetch();expect(response.status()).toBe(200);const raw=await h.snapshot();expect(raw.payments).toHaveLength(1);expect(raw.orders.find(row=>row.id===ids.O1)?.total).toBe(scenario.remaining);lost=true;await route.abort('failed');
  });
  await page.getByTestId('pay-button-footer').click();await expect(page.getByTestId('write-attempt-notice')).toBeVisible();await page.waitForTimeout(5200);expect(writes).toHaveLength(2);const original=writes[1].body;
  await page.getByRole('button',{name:'Thử lại cùng lệnh',exact:true}).click();await expect.poll(()=>writes.filter(request=>request.name==='execute_write_operation').length).toBe(2);
  expect(writes).toHaveLength(3);expect(writes[2].body).toEqual(original);expect(original.p_payload.kind).toBe('pay_order_items');expect(original.p_payload.expectedVersion).toBe(5);const raw=await h.snapshot(`TC-IDEM-${scenario.id}-e2e`);expect(raw.payments).toHaveLength(1);expect(raw.orders.find(row=>row.id===ids.O1)).toMatchObject({status:'open',total:scenario.remaining});expect(await printCount(page)).toBe(0);await expect(page.getByTestId('receipt-preview')).toBeHidden();
});
test('TC-IDEM-001/e2e real store pairing employee PIN acknowledged lock and reload',async({page})=>{
  await h.reset();let employeeToken='';page.on('request',request=>{const token=request.headers()['x-pos-employee-token'];if(token)employeeToken=token;});await pairAndUnlock(page);
  const stored=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));if(employeeToken&&stored.includes(employeeToken))throw new Error('Employee credential persisted in browser storage');
  await page.getByTestId('nav-lock').click();await expect(page.getByTestId('passcode-screen')).toBeVisible();await unlock(page);await page.reload();await expect(page.getByTestId('passcode-screen')).toBeVisible();await expect(page.getByTestId('store-pairing-screen')).toBeHidden();
});
test('TC-IDEM-038/e2e full cash confirmation displays literal receipt total and change',async({page})=>{
  await h.reset('F1');await installPrintCounter(page);await pairAndUnlock(page);await openPayment(page);await page.getByTestId('payment-received-amount').fill('200000');await page.getByTestId('pay-button-footer').click();await expect(page.getByTestId('receipt-preview')).toContainText('150.000');await expect(page.getByTestId('receipt-preview')).toContainText('50.000');
  const raw=await h.snapshot('TC-IDEM-038-e2e');expect(raw.payments).toHaveLength(1);expect(raw.payments[0]).toMatchObject({amount:150000,received_amount:200000,change_amount:50000,employee_id:ids.A});expect(await printCount(page)).toBe(0);
});
test('TC-IDEM-042/e2e full selection registers pay before execution and never registers split',async({page})=>{
  await h.reset('F1');await pairAndUnlock(page);const writes=watchWrites(page);await openPayment(page);await page.getByTestId('pay-button-footer').click();await expect.poll(async()=>(await h.snapshot()).payments.length).toBe(1);
  expect(writes.map(request=>request.name)).toEqual(['register_write_operation','execute_write_operation']);expect(writes[0].body.p_payload.kind).toBe('pay_order');expect(writes[1].body.p_operation_id).toBe(writes[0].body.p_operation_id);expect(writes[1].body.p_payload).toEqual(writes[0].body.p_payload);
});
test('TC-IDEM-050/e2e modifier quantity renders forty thousand per unit and eighty thousand total',async({page})=>{
  await h.reset('F7');await installPrintCounter(page);await pairAndUnlock(page);await openPayment(page);await page.getByTestId('payment-received-amount').fill('100000');await page.getByTestId('pay-button-footer').click();const preview=page.getByTestId('receipt-preview');await expect(preview).toContainText('40.000');await expect(preview).toContainText('80.000');await expect(preview).toContainText('Topping cũ');await expect(preview).toContainText(/×\s*2|x\s*2/);expect(await printCount(page)).toBe(0);await preview.getByRole('button',{name:'In',exact:true}).click();await expect.poll(()=>printCount(page)).toBe(1);
});
test('TC-IDEM-054/e2e offline and reconnect never enqueue or automatically resume a write',async({page,context})=>{
  await h.reset('F1');await pairAndUnlock(page);await openPayment(page);const writes=watchWrites(page);await context.setOffline(true);await expect(page.getByTestId('pay-button-footer')).toBeDisabled();await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(1000);expect(writes).toHaveLength(0);expect((await h.snapshot()).payments).toHaveLength(0);
});
test('TC-IDEM-052/e2e a late payment ACK after timeout cannot issue another write or print',async({page})=>{
  await h.reset('F1');await installPrintCounter(page);await pairAndUnlock(page);await openPayment(page);const writes=watchWrites(page);let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let committed=false;
  await page.route('**/rest/v1/rpc/execute_write_operation',async route=>{const response=await route.fetch();const raw=await h.snapshot();expect(raw.payments).toHaveLength(1);committed=true;await held;await route.fulfill({response});});
  await page.getByTestId('pay-button-footer').click();await expect.poll(()=>committed).toBe(true);await expect(page.getByTestId('write-attempt-notice')).toBeVisible({timeout:20000});expect(writes).toHaveLength(2);release();await page.waitForTimeout(1000);expect(writes).toHaveLength(2);expect(await printCount(page)).toBe(0);await expect(page.getByTestId('receipt-preview')).toBeHidden();
});
test('TC-IDEM-053/e2e a late registration ACK after timeout never starts execution automatically',async({page})=>{
  await h.reset();await installPrintCounter(page);await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await page.getByTestId(`menu-item-${ids.M_T}`).click();const writes=watchWrites(page);let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});
  await page.route('**/rest/v1/rpc/register_write_operation',async route=>{const response=await route.fetch();expect((await h.snapshot()).write_operations).toHaveLength(1);await held;await route.fulfill({response});});
  await page.getByTestId('submit-order-button-footer').click();await expect(page.getByTestId('write-attempt-notice')).toBeVisible({timeout:20000});release();await page.waitForTimeout(1000);expect(writes.map(request=>request.name)).toEqual(['register_write_operation']);expect((await h.snapshot()).orders).toHaveLength(0);expect(await printCount(page)).toBe(0);
});
test('TC-IDEM-090/e2e recovery results expose actor IDs without persisting employee credentials',async({page})=>{
  await h.reset('F1');const a=await h.login();await h.register(payPayload(),a);const b=await h.login('B');await h.execute(payPayload(),b);let token='';page.on('request',request=>{token=request.headers()['x-pos-employee-token']??token;});await pairAndUnlock(page,'B');await openRecovery(page);await expect(page.getByTestId('historical-result')).toContainText('150.000');const stored=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));if(token&&stored.includes(token))throw new Error('Employee token leaked to storage');const body=await page.locator('body').innerText();for(const secret of [token,a,b])if(secret&&body.includes(secret))throw new Error('Employee token leaked to rendered result');
});
test('TC-IDEM-092/e2e zero and empty selections are blocked while a mixed full selection pays twenty thousand',async({page,browser})=>{
  await h.reset('F1');await h.observer(async db=>{await db.query('update public.orders set subtotal=0,total=0 where id=$1',[ids.O1]);await db.query('update public.order_items set unit_price=0 where id=$1',[ids.L1]);});await pairAndUnlock(page);await openPayment(page);const writes=watchWrites(page);await expect(page.getByTestId('pay-button-footer')).toBeDisabled();await page.getByTestId('pay-item-checkbox').uncheck();await expect(page.getByTestId('pay-button-footer')).toBeDisabled();expect(writes).toHaveLength(0);expect((await h.snapshot()).payments).toHaveLength(0);await page.close();
  await h.reset('F1');await h.observer(async db=>{await db.query('update public.orders set total=20000,subtotal=20000 where id=$1',[ids.O1]);await db.query('update public.order_items set unit_price=0,quantity=1 where id=$1',[ids.L1]);await db.query("insert into public.order_items(id,store_id,order_id,menu_item_id,item_name,quantity,unit_price) values($1,$2,$3,$4,'Trà',1,20000)",[ids.L30,ids.S1,ids.O1,ids.M_T]);});const context=await browser.newContext({baseURL:'http://127.0.0.1:5176'});
  try{const other=await context.newPage();await pairAndUnlock(other);await openPayment(other);const requests=watchWrites(other);await other.getByTestId('pay-select-all').uncheck();await other.locator('[data-testid="pay-item-line"][data-unit-total="0"]').getByTestId('pay-item-checkbox').check();await expect(other.getByTestId('pay-button-footer')).toBeDisabled();expect(requests).toHaveLength(0);await other.getByTestId('pay-select-all').check();await expect(other.getByTestId('pay-button-footer')).toBeEnabled();await other.getByTestId('pay-button-footer').click();await expect.poll(async()=>(await h.snapshot()).payments.length).toBe(1);const raw=await h.snapshot();expect(raw.payments[0]).toMatchObject({amount:20000,received_amount:20000,change_amount:0});}finally{await context.close();}
});
