import { expect, test } from '@playwright/test';
import { ids } from '../contracts/fixtures.ts';
import { pairAndUnlock, openPayment, closeReceipt, serverHarness as h } from './idempotencyHarness.ts';
test.afterEach(()=>h.clock(null));
async function addA(page:any,option:'zero'|'doubleQ'='zero'){
  await page.getByTestId(`menu-item-${ids.M_A}`).click();await page.getByTestId(`modifier-value-${option==='zero'?ids.Z:ids.Q}`).click();if(option==='doubleQ')await page.getByTestId(`modifier-qty-inc-${ids.Q}`).click();await page.getByTestId('modifier-confirm').click();
}
async function submitted(page:any){await page.getByTestId('submit-order-button-footer').click();await expect(page.getByTestId('order-drawer')).toBeHidden();await closeReceipt(page);}
test('TC-IDEM-025/e2e old two coffees remain thirty thousand while a new coffee with the same free modifier costs forty thousand',async({page})=>{
  await h.reset('F5');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await addA(page);await expect(page.getByTestId('order-total-amount')).toHaveAttribute('data-amount','100000');await submitted(page);const raw=await h.snapshot();expect(raw.order_items.find(row=>row.id===ids.L1)).toMatchObject({quantity:2,unit_price:30000});expect(raw.order_items.filter(row=>row.id!==ids.L1)).toHaveLength(1);expect(raw.orders.find(row=>row.id===ids.O1)).toMatchObject({total:100000,lock_version:6});
});
test('TC-IDEM-026/e2e plus on a saved line creates a separate portion at the current price',async({page})=>{
  await h.reset('F5');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await page.getByTestId('order-cart-increase').first().click();await expect(page.getByTestId('order-cart-line')).toHaveCount(2);await expect(page.getByTestId('order-total-amount')).toHaveAttribute('data-amount','100000');await submitted(page);const raw=await h.snapshot();expect(raw.order_items.find(row=>row.id===ids.L1)).toMatchObject({quantity:2,unit_price:30000});expect(raw.order_items.find(row=>row.id!==ids.L1)).toMatchObject({quantity:1,unit_price:40000});
});
test('TC-IDEM-027/e2e note edits between different priced portions are dirty and preserve both source identities',async({page})=>{
  await h.reset('F2');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();const first=page.getByTestId('order-cart-line').filter({hasText:'30.000'});const second=page.getByTestId('order-cart-line').filter({hasText:'35.000'});await first.getByRole('button',{name:'Ghi chú',exact:true}).click();await first.getByPlaceholder('VD: ít đá, không đường...').fill('');await second.getByRole('button',{name:'Ghi chú',exact:true}).click();await second.getByPlaceholder('VD: ít đá, không đường...').fill('ít đá');await submitted(page);const raw=await h.snapshot();expect(raw.order_items.find(row=>row.id===ids.L30)).toMatchObject({unit_price:30000,note:null});expect(raw.order_items.find(row=>row.id===ids.L35)).toMatchObject({unit_price:35000,note:'ít đá'});expect(raw.payments).toHaveLength(0);
});
for(const variant of ['new','old'] as const)test(`TC-IDEM-030/e2e${variant==='old'?'/old':''} double modifier preserves identities and prices when splitting the ${variant} portion`,async({page})=>{
  await h.reset('F3');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await addA(page,'doubleQ');await expect(page.getByTestId('order-total-amount')).toHaveAttribute('data-amount','129000');await submitted(page);
  const before=await h.snapshot();expect(before.order_items).toHaveLength(2);expect(before.order_item_options).toHaveLength(2);const newLine=before.order_items.find(row=>row.id!==ids.L1)!;
  expect(before.order_items.find(row=>row.id===ids.L1)).toMatchObject({menu_item_id:ids.M_A,item_name:'Cà phê cũ',quantity:2,unit_price:30000});expect(newLine).toMatchObject({order_id:ids.O1,menu_item_id:ids.M_A,item_name:'Cà phê mới',quantity:1,unit_price:35000});
  expect(before.order_item_options.find(row=>row.id===ids.OPTION1)).toMatchObject({order_item_id:ids.L1,option_value_id:ids.Q,option_name:'Topping cũ',quantity:2,price_delta:5000});expect(before.order_item_options.find(row=>row.order_item_id===newLine.id)).toMatchObject({option_value_id:ids.Q,option_name:'Topping mới',quantity:2,price_delta:7000});
  await openPayment(page);await page.getByTestId('pay-select-all').uncheck();const chosen=page.locator(`[data-testid="pay-item-line"][data-unit-total="${variant==='new'?49000:40000}"]`);await expect(chosen).toContainText(variant==='new'?'Cà phê mới':'Cà phê cũ');await chosen.getByTestId('pay-item-checkbox').check();await expect(chosen).toHaveAttribute('data-selected-quantity','1');await page.getByTestId('payment-received-amount').fill('50000');await page.getByTestId('pay-button-footer').click();await expect.poll(async()=>(await h.snapshot()).payments.length).toBe(1);
  const raw=await h.snapshot();const amount=variant==='new'?49000:40000;const payment=raw.payments[0];expect(payment).toMatchObject({amount,received_amount:50000,change_amount:50000-amount});expect(raw.orders.find(row=>row.id===ids.O1)).toMatchObject({total:variant==='new'?80000:89000,status:'open',lock_version:7});expect(raw.orders.find(row=>row.id===payment.order_id)).toMatchObject({total:amount,status:'paid'});
  expect(raw.order_items).toHaveLength(variant==='new'?2:3);const copied=raw.order_items.find(row=>row.order_id===payment.order_id)!;const original=before.order_items.find(row=>row.id===(variant==='new'?newLine.id:ids.L1))!;expect(copied).toMatchObject({menu_item_id:ids.M_A,item_name:original.item_name,quantity:1,unit_price:original.unit_price,note:original.note});if(variant==='new')expect(copied.id).toBe(newLine.id);else expect([ids.L1,newLine.id]).not.toContain(copied.id);
  expect(raw.order_items.find(row=>row.id===ids.L1)).toMatchObject({quantity:variant==='new'?2:1,unit_price:30000,item_name:'Cà phê cũ',status:'waiting'});expect(raw.order_items.find(row=>row.id===newLine.id)).toMatchObject({quantity:1,unit_price:35000,item_name:'Cà phê mới',status:'waiting',order_id:variant==='new'?payment.order_id:ids.O1});
  expect(raw.order_item_options).toHaveLength(variant==='new'?2:3);expect(raw.order_item_options.filter(row=>variant==='new'||row.order_item_id!==copied.id)).toEqual(before.order_item_options);const copiedOption=raw.order_item_options.find(row=>row.order_item_id===copied.id)!;expect(copiedOption).toMatchObject({option_value_id:ids.Q,option_name:variant==='new'?'Topping mới':'Topping cũ',quantity:2,price_delta:variant==='new'?7000:5000});if(variant==='old')expect(before.order_item_options.map(row=>row.id)).not.toContain(copiedOption.id);else expect(copiedOption.id).toBe(before.order_item_options.find(row=>row.order_item_id===newLine.id)!.id);
  expect(payment.receipt_snapshot).toMatchObject({total:amount,lines:[{orderItemId:copied.id,name:original.item_name,quantity:1,baseUnitPrice:original.unit_price,lineTotal:amount,options:[{optionValueId:ids.Q,name:copiedOption.option_name,quantity:2,priceDelta:copiedOption.price_delta}]}]});
});
test('TC-IDEM-034/e2e a changed new-item quote requires a new explicit confirmation',async({page})=>{
  await h.reset('F5');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await addA(page);await h.observer(db=>db.query('update public.menu_items set price=45000 where id=$1',[ids.M_A]));await page.getByTestId('submit-order-button-footer').click();await expect(page.getByTestId('price-changed-review')).toBeVisible();expect((await h.snapshot()).orders.find(row=>row.id===ids.O1)?.total).toBe(60000);await page.getByRole('button',{name:'Dùng giá mới để kiểm tra lại giỏ',exact:true}).click();await expect(page.getByTestId('order-total-amount')).toHaveAttribute('data-amount','105000');expect((await h.snapshot()).orders.find(row=>row.id===ids.O1)?.total).toBe(60000);await submitted(page);expect((await h.snapshot()).orders.find(row=>row.id===ids.O1)?.total).toBe(105000);
});
test('TC-IDEM-035/e2e offsetting base and modifier changes still require confirmation despite an unchanged total',async({page})=>{
  await h.reset('F3');await pairAndUnlock(page);await page.getByTestId(`table-${ids.B01}`).click();await addA(page,'doubleQ');await h.observer(async db=>{await db.query('update public.menu_items set price=37000 where id=$1',[ids.M_A]);await db.query('update public.option_values set price_delta=6000 where id=$1',[ids.Q]);});await page.getByTestId('submit-order-button-footer').click();await expect(page.getByTestId('price-changed-review')).toBeVisible();expect((await h.snapshot()).orders.find(row=>row.id===ids.O1)?.total).toBe(80000);await page.getByRole('button',{name:'Dùng giá mới để kiểm tra lại giỏ',exact:true}).click();await expect(page.getByTestId('order-total-amount')).toHaveAttribute('data-amount','129000');await submitted(page);expect((await h.snapshot()).orders.find(row=>row.id===ids.O1)?.total).toBe(129000);
});
